### ISSUE TITLE
No ongoing indication that omdb config is saved

### ISSUE THREAD

**Issue by TobyHFerguson** [redis-developer/redis-microservices-demo#37] opened 2020-10-21 21:00 UTC
If one clicks the 'save' button for the OMDB key then one sees that the key has been saved. But if one leaves the page and comes back there's no indication that that key has been saved ...

**Comment by tgrall** [comment] 2020-10-22 06:08
Can you clarify?

I am not sure to understand, if the issue is because somebody set the value and forget to click save or something else?
If this is the case it is true for all forms in the demonstration.

Maybe I do not understand the issue.

@TobyHFerguson please clarify

**Comment by TobyHFerguson** [comment] 2020-10-27 20:32
Tug - I guess its taken me a little while to understand that when I see this:

![image](https://user-images.githubusercontent.com/6525189/97358416-77bd1080-1858-11eb-9aa4-5951d67a7f60.png)

that that means that the OMDB key has been saved, and is being shown here. I think what happened is I pressed 'SAVE', and saw this:

![image](https://user-images.githubusercontent.com/6525189/97358565-a9ce7280-1858-11eb-97b8-7eba8f4cab1e.png)

so then assumed that I had to press 'Save' to get that 'Configuration Saved' message. (I've only now figured out that that message goes away - it happens to be just about off my screen on my mac so I wasn't paying close attention to it).

This is a minor issue, but I'm trying to record everything for now so that we don't lose track of what issues I have.

**Comment by tgrall** [comment] 2020-10-28 08:36
Each form: Movie, Actor and Service have the same behavior.
When you click save a small notification is showed, and disappears after few seconds.

I am closing the bug to keep track of the progress, feel free to reopen if you think this is not good

**Closed as completed by tgrall** 2020-10-28 08:36 UTC
Labels: bug, question
